# Debugging

In [1]:
import numpy as np
import pandas as pd
from numpy import dot,sum

In [2]:
def featureNormalize(X):
      mean_array=X.mean(0)
      std_array=X.std(0, ddof=1)
      mean_for_area=mean_array[0]
      mean_for_rooms=mean_array[1]
      std_area=std_array[0]
      std_rooms=std_array[1]
      X[:,0]=(X[:,0]-mean_for_area)/std_area
      X[:,1]=(X[:,1]-mean_for_rooms)/std_rooms
 
      return (X,mean_array,std_array)

In [3]:
def addOnes(X):
      n=X.shape[0]
      ones=np.ones(n).reshape(n,1)
      return np.concatenate((ones,X),1)


In [6]:
data=pd.read_csv('ex1data2.txt',header=None,names = ["Area", "No of bedrooms","Price"])
matrix=pd.DataFrame.as_matrix(data)
X=np.array([data['Area'],data['No of bedrooms']], dtype=np.float64)
X=np.transpose(X)
(X,mean_array,std_array)=featureNormalize(X)
X=addOnes(X)
theta=np.zeros((3,1), dtype=np.float64)
alpha,num_iters=0.01,400
y=np.array(data['Price'])
m=len(y)
y=y.reshape(m,1)
h=dot(X,theta)
x=h-y

In [7]:
t1=X[:,0].reshape(m,1)
t2=X[:,1].reshape(m,1)
t3=X[:,2].reshape(m,1)
theta[0] -= (alpha /m) * np.sum(x)
theta[1] -= (alpha /m) * np.sum(x*t2)
theta[2] -= (alpha /m) * np.sum(x*t3)

In [8]:
theta

array([[ 3404.12659574],
       [ 1046.32933766],
       [  541.23683844]])

In [10]:
t1=X[:,0].reshape(m,1)
t2=X[:,1].reshape(m,1)
t3=X[:,2].reshape(m,1)
h=dot(X,theta)
x=h-y

In [11]:
 theta[1] -= (alpha /m) * np.sum(x*t2)

In [12]:
theta[1]

array([ 1046.32933766])

In [41]:
(alpha /m) * np.sum(x*t2)

-1046.3293376618246

In [13]:
(alpha /m) * np.sum(x*t3)

-541.23683844075845

In [37]:
np.sum(x*t2)

-4917747.8870105762

In [14]:
x = h-y

In [24]:
x[0] * X[0,1]

array([-51990.94664291])

In [25]:
x[1] * X[1,1]

array([ 166332.22762983])

In [15]:
np.sum(h-y)

-15999395.0

In [29]:
(X[:,1]).shape

(47,)

In [16]:
x=(h-y)

In [17]:
theta[0] -= (alpha /m) * np.sum(x)

In [18]:
theta[0]

array([ 3404.12659574])

In [19]:
theta[1] -= (alpha /m) * (np.sum(x * X[:,1]))

In [20]:
theta

array([[  3.40412660e+03],
       [  3.76492105e-12],
       [  0.00000000e+00]])

In [35]:
a

array([[-399900.],
       [-329900.],
       [-369000.],
       [-232000.],
       [-539900.],
       [-299900.],
       [-314900.],
       [-198999.],
       [-212000.],
       [-242500.],
       [-239999.],
       [-347000.],
       [-329999.],
       [-699900.],
       [-259900.],
       [-449900.],
       [-299900.],
       [-199900.],
       [-499998.],
       [-599000.],
       [-252900.],
       [-255000.],
       [-242900.],
       [-259900.],
       [-573900.],
       [-249900.],
       [-464500.],
       [-469000.],
       [-475000.],
       [-299900.],
       [-349900.],
       [-169900.],
       [-314900.],
       [-579900.],
       [-285900.],
       [-249900.],
       [-229900.],
       [-345000.],
       [-549000.],
       [-287000.],
       [-368500.],
       [-329900.],
       [-314000.],
       [-299000.],
       [-179900.],
       [-299900.],
       [-239500.]])

In [32]:
theta[1]

array([  1.51092226e-12])

In [33]:
X[:,1]

array([  1.31415422e-01,  -5.09640698e-01,   5.07908699e-01,
        -7.43677059e-01,   1.27107075e+00,  -1.99450507e-02,
        -5.93588523e-01,  -7.29685755e-01,  -7.89466782e-01,
        -6.44465993e-01,  -7.71822042e-02,  -8.65999486e-04,
        -1.40779041e-01,   3.15099326e+00,  -9.31923697e-01,
         3.80715024e-01,  -8.65782986e-01,  -9.72625673e-01,
         7.73743478e-01,   1.31050078e+00,  -2.97227261e-01,
        -1.43322915e-01,  -5.04552951e-01,  -4.91995958e-02,
         2.40309445e+00,  -1.14560907e+00,  -6.90255715e-01,
         6.68172729e-01,   2.53521350e-01,   8.09357707e-01,
        -2.05647815e-01,  -1.27280274e+00,   5.00114703e-02,
         1.44532608e+00,  -2.41262044e-01,  -7.16966387e-01,
        -9.68809863e-01,   1.67029651e-01,   2.81647389e+00,
         2.05187753e-01,  -4.28236746e-01,   3.01854946e-01,
         7.20322135e-01,  -1.01841540e+00,  -1.46104938e+00,
        -1.89112638e-01,  -1.01459959e+00])

In [26]:
t1=(dot(X,theta)-y).transpose()

In [28]:
t2=dot(X,theta)-y

In [33]:
dot(t1,t2)/(2*m)

array([[  6.55915481e+10]])